#!/bin/bash
#
# app-setup.sh - Application deployment and configuration
# Clones repository, generates .env, installs dependencies, runs migrations
#

set -euo pipefail

# Source common functions
SERVICE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=./lib/common.sh
source "${SCRIPT_DIR}/lib/common.sh"
# shellcheck source=./lib/validators.sh
source "${SCRIPT_DIR}/lib/validators.sh"

# Application configuration
readonly APP_DIR="/opt/server-manager"
readonly DEPLOY_USER="deploy"
readonly REPO_URL="${REPO_URL:-https://github.com/Pwoodlock/veracity-.git}"
readonly REPO_BRANCH="${REPO_BRANCH:-main}"

#######################################
# Clone or update repository
#######################################
clone_repository() {
  section "Setting up Application"

  if [ -d "${APP_DIR}" ]; then
    warning "Application directory already exists: ${APP_DIR}"

    if confirm "Do you want to backup and re-clone?" "n"; then
      local backup_dir="${APP_DIR}.backup.$(date +%Y%m%d-%H%M%S)"
      step "Backing up to: ${backup_dir}"
      execute mv "${APP_DIR}" "${backup_dir}"
    else
      info "Using existing application directory"
      return 0
    fi
  fi

  step "Cloning repository from ${REPO_URL}..."

  # Clone as root first, then change ownership
  execute git clone --depth 1 --branch "${REPO_BRANCH}" "${REPO_URL}" "${APP_DIR}"

  # Remove unnecessary files to reduce disk usage (saves ~86MB)
  info "Removing unnecessary files (test, docs, .github, vendor/bundle)..."
  execute rm -rf "${APP_DIR}/test"
  execute rm -rf "${APP_DIR}/docs"
  execute rm -rf "${APP_DIR}/.github"
  execute rm -rf "${APP_DIR}/vendor/bundle"
  execute rm -rf "${APP_DIR}/node_modules" 2>/dev/null || true
  success "Removed unnecessary files (saved ~86MB)"

  # Set ownership to deploy user
  execute chown -R "${DEPLOY_USER}:${DEPLOY_USER}" "${APP_DIR}"

  success "Repository cloned successfully"
}

#######################################
# Generate .env.production file
# Globals: All configuration variables
#######################################
generate_env_file() {
  step "Generating .env.production file..."

  local env_file="${APP_DIR}/.env.production"

  # Backup existing .env if present
  if [ -f "${env_file}" ]; then
    local backup="${env_file}.backup.$(date +%Y%m%d-%H%M%S)"
    execute cp "${env_file}" "${backup}"
    info "Backed up existing .env to: ${backup}"
  fi

  # Generate .env.production
  cat > "${env_file}" << EOF
# ============================================================================
# VERACITY PRODUCTION CONFIGURATION
# Auto-generated by installer on $(date)
# ============================================================================

# ============================================================================
# RAILS CONFIGURATION
# ============================================================================
RAILS_ENV=production
RAILS_LOG_LEVEL=${RAILS_LOG_LEVEL:-info}
SECRET_KEY_BASE=${SECRET_KEY_BASE}

# Domain/Host Configuration
RAILS_HOST=${RAILS_HOST}
RAILS_PROTOCOL=${RAILS_PROTOCOL:-https}
RAILS_FORCE_SSL=${RAILS_FORCE_SSL:-true}
RAILS_SERVE_STATIC_FILES=true
RAILS_MAX_THREADS=${RAILS_MAX_THREADS:-10}

# ============================================================================
# DATABASE CONFIGURATION
# ============================================================================
DATABASE_USERNAME=${DB_USER}
DATABASE_PASSWORD=${DB_PASSWORD}
DATABASE_HOST=${DB_HOST:-localhost}

# ============================================================================
# REDIS CONFIGURATION
# ============================================================================
REDIS_URL=${REDIS_URL:-redis://localhost:6379/0}

# ============================================================================
# SALT API CONFIGURATION
# ============================================================================
SALT_API_URL=${SALT_API_URL:-http://localhost:8001}
SALT_API_USERNAME=${SALT_API_USER}
SALT_API_PASSWORD=${SALT_API_PASSWORD}
SALT_API_EAUTH=${SALT_API_EAUTH:-pam}

# ============================================================================
# EMAIL CONFIGURATION (Optional)
# ============================================================================
$(if [ -n "${SMTP2GO_USERNAME:-}" ]; then
cat << SMTP
SMTP2GO_USERNAME=${SMTP2GO_USERNAME}
SMTP2GO_PASSWORD=${SMTP2GO_PASSWORD}
MAILER_HOST=${RAILS_HOST}
MAILER_FROM=${MAILER_FROM:-noreply@${RAILS_HOST}}
SMTP
else
echo "# SMTP2GO_USERNAME="
echo "# SMTP2GO_PASSWORD="
echo "# MAILER_HOST=${RAILS_HOST}"
echo "# MAILER_FROM=noreply@${RAILS_HOST}"
fi)

# ============================================================================
# GOTIFY PUSH NOTIFICATIONS
# ============================================================================
GOTIFY_ENABLED=${GOTIFY_ENABLED:-true}
GOTIFY_URL=${GOTIFY_URL:-http://localhost:8080}
GOTIFY_APP_TOKEN=${GOTIFY_APP_TOKEN:-}
GOTIFY_SSL_VERIFY=true

# ============================================================================
# OAUTH2 / ZITADEL (Optional)
# ============================================================================
$(if [ "${OAUTH_ENABLED:-false}" = "true" ]; then
cat << OAUTH
ZITADEL_CLIENT_ID=${ZITADEL_CLIENT_ID}
ZITADEL_ISSUER=${ZITADEL_ISSUER}
OAUTH
else
echo "# ZITADEL_CLIENT_ID="
echo "# ZITADEL_ISSUER="
fi)

# ============================================================================
# CVE MONITORING
# ============================================================================
VULNERABILITY_LOOKUP_ENABLED=${CVE_ENABLED:-true}
VULNERABILITY_LOOKUP_URL=${CVE_URL:-https://vulnerability.circl.lu}
VULNERABILITY_LOOKUP_SCAN_SCHEDULE=${CVE_SCHEDULE:-0 2 * * *}
VULNERABILITY_LOOKUP_PYTHON_PATH=${VULNERABILITY_LOOKUP_PYTHON_PATH:-/opt/server-manager/bin/cve_python}
VULNERABILITY_LOOKUP_TIMEOUT=60

# ============================================================================
# PROXMOX API (Configure via UI)
# ============================================================================
# PROXMOX_API_TOKENS stored encrypted in database

# ============================================================================
# HETZNER CLOUD (Configure via UI)
# ============================================================================
# HETZNER_API_TOKENS stored encrypted in database

# ============================================================================
# SYSTEM CONFIGURATION
# ============================================================================
TZ=${TZ:-UTC}
PORT=3000
WEB_CONCURRENCY=${WEB_CONCURRENCY:-2}
SOLID_QUEUE_IN_PUMA=false
EOF

  # Set secure permissions
  execute chown "${DEPLOY_USER}:${DEPLOY_USER}" "${env_file}"
  execute chmod 600 "${env_file}"

  success ".env.production file generated"
}

#######################################
# Install Ruby gems
#######################################
install_gems() {
  step "Installing Ruby gems (this may take several minutes)..."

  cd "${APP_DIR}"

  # Install gems as deploy user
  if ! sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && bundle config set --local deployment 'true' && bundle install --jobs=4 --retry=3" >> "${LOG_FILE}" 2>&1; then
    fatal "Failed to install gems. Check ${LOG_FILE} for details"
  fi

  success "Gems installed successfully"
}

#######################################
# Install Node packages
#######################################
install_node_packages() {
  step "Installing Node.js packages..."

  cd "${APP_DIR}"

  # Install packages as deploy user
  if ! sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && yarn install --frozen-lockfile" >> "${LOG_FILE}" 2>&1; then
    fatal "Failed to install Node packages. Check ${LOG_FILE} for details"
  fi

  success "Node packages installed successfully"
}

#######################################
# Setup database
#######################################
setup_database() {
  step "Setting up database..."

  cd "${APP_DIR}"

  # Load environment and run database setup
  info "Creating database schema..."

  if ! sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && RAILS_ENV=production bundle exec rails db:create db:schema:load" >> "${LOG_FILE}" 2>&1; then
    # Try with migrations if schema load fails
    warning "Schema load failed, trying with migrations..."
    if ! sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && RAILS_ENV=production bundle exec rails db:create db:migrate" >> "${LOG_FILE}" 2>&1; then
      fatal "Failed to setup database. Check ${LOG_FILE} for details"
    fi
  fi

  # Load seeds if present
  if [ -f "${APP_DIR}/db/seeds.rb" ]; then
    info "Loading database seeds..."
    sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && RAILS_ENV=production bundle exec rails db:seed" >> "${LOG_FILE}" 2>&1 || true
  fi

  success "Database setup complete"
}

#######################################
# Precompile assets
#######################################
precompile_assets() {
  step "Precompiling assets (this may take a few minutes)..."

  cd "${APP_DIR}"

  # Precompile assets as deploy user
  if ! sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && RAILS_ENV=production bundle exec rails assets:precompile" >> "${LOG_FILE}" 2>&1; then
    fatal "Failed to precompile assets. Check ${LOG_FILE} for details"
  fi

  success "Assets precompiled successfully"
}

#######################################
# Create admin user
#######################################
create_admin_user() {
  step "Creating admin user..."

  cd "${APP_DIR}"

  # Create admin user via Rails console
  local create_admin_script="
    user = User.find_or_initialize_by(email: '${ADMIN_EMAIL}')
    user.password = '${ADMIN_PASSWORD}'
    user.password_confirmation = '${ADMIN_PASSWORD}'
    user.role = 'admin'
    user.skip_confirmation! if user.respond_to?(:skip_confirmation!)

    if user.save
      puts 'Admin user created successfully'
    else
      puts \"Failed to create admin user: #{user.errors.full_messages.join(', ')}\"
      exit 1
    end
  "

  if sudo -u "${DEPLOY_USER}" bash -lc "cd ${APP_DIR} && RAILS_ENV=production bundle exec rails runner \"${create_admin_script}\"" >> "${LOG_FILE}" 2>&1; then
    success "Admin user created: ${ADMIN_EMAIL}"
  else
    warning "Failed to create admin user automatically"
    warning "You can create it manually after installation via Rails console"
  fi
}

#######################################
# Setup log rotation
#######################################
setup_log_rotation() {
  step "Configuring log rotation..."

  cat > /etc/logrotate.d/veracity << EOF
${APP_DIR}/log/*.log {
    daily
    missingok
    rotate 14
    compress
    delaycompress
    notifempty
    copytruncate
    su ${DEPLOY_USER} ${DEPLOY_USER}
}
EOF

  success "Log rotation configured"
}

#######################################
# Create necessary directories
#######################################
create_app_directories() {
  step "Creating application directories..."

  local dirs=(
    "${APP_DIR}/tmp"
    "${APP_DIR}/tmp/pids"
    "${APP_DIR}/tmp/cache"
    "${APP_DIR}/tmp/sockets"
    "${APP_DIR}/log"
    "${APP_DIR}/public/assets"
    "${APP_DIR}/storage"
  )

  for dir in "${dirs[@]}"; do
    mkdir -p "${dir}"
    chown "${DEPLOY_USER}:${DEPLOY_USER}" "${dir}"
  done

  success "Application directories created"
}

#######################################
# Setup application for Veracity
# Main function that orchestrates application setup
#######################################
setup_application() {
  clone_repository
  create_app_directories
  generate_env_file
  install_gems
  install_node_packages
  setup_database
  precompile_assets
  create_admin_user
  setup_log_rotation

  success "Application setup complete!"

  info "Application: ${APP_DIR}"
  info "Environment: production"
  info "Deploy user: ${DEPLOY_USER}"
}

# If script is executed directly, run setup
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  # Validate required environment variables
  local required_vars=(
    "SECRET_KEY_BASE"
    "DB_USER"
    "DB_PASSWORD"
    "SALT_API_USER"
    "SALT_API_PASSWORD"
    "ADMIN_EMAIL"
    "ADMIN_PASSWORD"
    "RAILS_HOST"
  )

  for var in "${required_vars[@]}"; do
    if [ -z "${!var:-}" ]; then
      fatal "Required environment variable not set: ${var}"
    fi
  done

  setup_application
fi
