# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Allow both single and double quoted strings
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
