# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style

# Allow both single and double quoted strings
Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false

# Existing codebase doesn't follow these rules
Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: false

Layout/EmptyLinesAroundMethodBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false
