#!/bin/bash
#
# caddy.sh - Caddy v2 installation and configuration
# Installs Caddy reverse proxy with automatic HTTPS via Let's Encrypt
#

set -euo pipefail

# Source common functions
SERVICE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SERVICE_SCRIPT_DIR}/../lib/common.sh"
# shellcheck source=../lib/validators.sh
source "${SERVICE_SCRIPT_DIR}/../lib/validators.sh"

#######################################
# Install Caddy
# Globals:
#   OS_ID
#######################################
install_caddy() {
  section "Installing Caddy v2"

  case "${OS_ID}" in
    ubuntu|debian)
      install_caddy_debian
      ;;
    rocky|almalinux|rhel)
      install_caddy_rhel
      ;;
    *)
      fatal "Unsupported OS for Caddy installation: ${OS_ID}"
      ;;
  esac
}

#######################################
# Install Caddy on Debian/Ubuntu
#######################################
install_caddy_debian() {
  step "Installing Caddy for Debian/Ubuntu..."

  # Install prerequisites
  install_packages debian-keyring debian-archive-keyring apt-transport-https curl

  # Add Caddy repository
  info "Adding Caddy repository..."

  execute curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
    -o /usr/share/keyrings/caddy-stable-archive-keyring.asc

  execute curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
    -o /etc/apt/sources.list.d/caddy-stable.list

  # Update and install
  execute apt-get update -qq
  spinner "Installing Caddy" install_packages caddy

  success "Caddy installed"
}

#######################################
# Install Caddy on RHEL/Rocky
#######################################
install_caddy_rhel() {
  step "Installing Caddy for RHEL/Rocky..."

  # Add Caddy repository
  info "Adding Caddy repository..."

  execute dnf install -y -q 'dnf-command(copr)'
  execute dnf copr enable -y @caddy/caddy

  # Install Caddy
  spinner "Installing Caddy" install_packages caddy

  success "Caddy installed"
}

#######################################
# Generate Caddyfile
# Creates Caddyfile with reverse proxy configuration
# Globals:
#   RAILS_HOST, ADMIN_EMAIL
#######################################
generate_caddyfile() {
  step "Generating Caddyfile..."

  local caddyfile="/etc/caddy/Caddyfile"
  local backup_file="/etc/caddy/Caddyfile.backup.$(date +%Y%m%d-%H%M%S)"

  # Backup existing Caddyfile if it exists
  if [ -f "${caddyfile}" ]; then
    execute cp "${caddyfile}" "${backup_file}"
    info "Backed up existing Caddyfile to: ${backup_file}"
  fi

  # Determine protocol and port
  local protocol="${RAILS_PROTOCOL:-https}"
  local port="3000"

  # Create Caddyfile based on protocol
  if [ "${protocol}" == "https" ]; then
    # Production configuration with automatic HTTPS
    cat > "${caddyfile}" << EOF
# Veracity - Caddy Configuration
# Auto-generated by Veracity installer
# Provides reverse proxy with automatic HTTPS via Let's Encrypt

${RAILS_HOST} {
    # Email for Let's Encrypt notifications
    tls ${ADMIN_EMAIL}

    # Encode responses with compression
    encode gzip zstd

    # Logging
    log {
        output file /var/log/caddy/veracity-access.log {
            roll_size 100mb
            roll_keep 10
            roll_keep_for 720h
        }
        format json
    }

    # Reverse proxy to Rails application
    reverse_proxy localhost:${port} {
        # Health check
        health_uri /up
        health_interval 10s
        health_timeout 5s

        # Headers
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}

        # Timeouts
        transport http {
            read_timeout 60s
            write_timeout 60s
            dial_timeout 10s
        }
    }

    # Security headers
    header {
        # Prevent MIME sniffing
        X-Content-Type-Options "nosniff"

        # XSS Protection
        X-XSS-Protection "1; mode=block"

        # Clickjacking protection
        X-Frame-Options "SAMEORIGIN"

        # Referrer policy
        Referrer-Policy "strict-origin-when-cross-origin"

        # Remove server header
        -Server
    }

    # Handle errors
    handle_errors {
        respond "{err.status_code} {err.status_text}"
    }
}

# Redirect www to non-www (if applicable)
www.${RAILS_HOST} {
    redir https://${RAILS_HOST}{uri} permanent
}

# Gotify push notification server
${GOTIFY_HOST} {
    # Email for Let's Encrypt notifications
    tls ${ADMIN_EMAIL}

    # Encode responses with compression
    encode gzip zstd

    # Logging
    log {
        output file /var/log/caddy/gotify-access.log {
            roll_size 100mb
            roll_keep 10
            roll_keep_for 720h
        }
        format json
    }

    # Reverse proxy to Gotify (Docker container)
    reverse_proxy localhost:${GOTIFY_PORT} {
        # Headers
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}

        # WebSocket support for Gotify
        header_up Connection {>Connection}
        header_up Upgrade {>Upgrade}
    }

    # Security headers
    header {
        X-Content-Type-Options "nosniff"
        X-XSS-Protection "1; mode=block"
        X-Frame-Options "SAMEORIGIN"
        Referrer-Policy "strict-origin-when-cross-origin"
        -Server
    }
}
EOF
  else
    # Development/HTTP only configuration
    cat > "${caddyfile}" << EOF
# Veracity - Caddy Configuration (HTTP Only)
# Auto-generated by Veracity installer

${RAILS_HOST} {
    # Disable automatic HTTPS
    auto_https off

    # Encode responses with compression
    encode gzip zstd

    # Logging
    log {
        output file /var/log/caddy/veracity-access.log
        format json
    }

    # Reverse proxy to Rails application
    reverse_proxy localhost:${port} {
        health_uri /up
        health_interval 10s
        health_timeout 5s

        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}
    }
}

# Gotify push notification server (HTTP)
${GOTIFY_HOST} {
    # Disable automatic HTTPS
    auto_https off

    # Encode responses with compression
    encode gzip zstd

    # Logging
    log {
        output file /var/log/caddy/gotify-access.log
        format json
    }

    # Reverse proxy to Gotify (Docker container)
    reverse_proxy localhost:${GOTIFY_PORT} {
        header_up X-Real-IP {remote_host}
        header_up X-Forwarded-For {remote_host}
        header_up X-Forwarded-Proto {scheme}
        header_up X-Forwarded-Host {host}

        # WebSocket support for Gotify
        header_up Connection {>Connection}
        header_up Upgrade {>Upgrade}
    }
}
EOF
  fi

  success "Caddyfile generated at: ${caddyfile}"
}

#######################################
# Create log directory for Caddy
#######################################
create_caddy_log_dir() {
  step "Creating Caddy log directory..."

  mkdir -p /var/log/caddy
  chown caddy:caddy /var/log/caddy
  chmod 755 /var/log/caddy

  success "Caddy log directory created"
}

#######################################
# Validate Caddyfile syntax
#######################################
validate_caddyfile() {
  step "Validating Caddyfile syntax..."

  if execute caddy validate --config /etc/caddy/Caddyfile; then
    success "Caddyfile syntax is valid"
  else
    fatal "Caddyfile syntax is invalid. Please check the configuration."
  fi
}

#######################################
# Start Caddy service
#######################################
start_caddy() {
  step "Starting Caddy service..."

  # Enable Caddy to start on boot
  execute systemctl enable caddy

  # Start Caddy
  execute systemctl restart caddy

  if wait_for_service caddy; then
    success "Caddy started successfully"
  else
    fatal "Failed to start Caddy"
  fi
}

#######################################
# Test Caddy reverse proxy
#######################################
test_caddy() {
  step "Testing Caddy configuration..."

  sleep 3  # Give Caddy time to fully start

  # Check if Caddy is listening on port 80/443
  if netstat -tuln | grep -q ":80 "; then
    success "Caddy is listening on port 80"
  else
    warning "Caddy is not listening on port 80"
  fi

  if [ "${RAILS_PROTOCOL}" == "https" ]; then
    if netstat -tuln | grep -q ":443 "; then
      success "Caddy is listening on port 443"
    else
      warning "Caddy is not listening on port 443 (may still be provisioning certificate)"
    fi
  fi

  # Display Caddy status
  systemctl status caddy --no-pager -l | head -10

  success "Caddy test complete"
}

#######################################
# Display Caddy information
#######################################
display_caddy_info() {
  section "Caddy Configuration"

  info "Caddy version: $(caddy version)"
  info "Domain: ${RAILS_HOST}"
  info "Protocol: ${RAILS_PROTOCOL}"
  info "Backend: http://localhost:3000"
  info "Caddyfile: /etc/caddy/Caddyfile"
  info "Logs: /var/log/caddy/"

  if [ "${RAILS_PROTOCOL}" == "https" ]; then
    echo ""
    info "Automatic HTTPS: Enabled"
    info "Certificate Provider: Let's Encrypt"
    info "Contact Email: ${ADMIN_EMAIL}"
    echo ""
    warning "Important: Ensure your domain DNS is correctly configured before accessing"
    warning "Let's Encrypt certificate will be provisioned on first access"
  else
    echo ""
    warning "Automatic HTTPS: Disabled (Development mode)"
    warning "Access via: http://${RAILS_HOST}"
  fi
}

#######################################
# Setup Caddy for Veracity
# Main function that orchestrates Caddy setup
# Globals:
#   RAILS_HOST, ADMIN_EMAIL, RAILS_PROTOCOL
#######################################
setup_caddy() {
  # Validate required environment variables
  if [ -z "${RAILS_HOST:-}" ]; then
    fatal "RAILS_HOST environment variable is required"
  fi

  if [ -z "${ADMIN_EMAIL:-}" ]; then
    fatal "ADMIN_EMAIL environment variable is required"
  fi

  install_caddy
  create_caddy_log_dir
  generate_caddyfile
  validate_caddyfile
  start_caddy
  test_caddy
  display_caddy_info

  success "Caddy setup complete!"
}

# If script is executed directly, run setup
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  setup_caddy
fi
