#!/bin/bash
#
# salt.sh - SaltStack Master and API installation
# Installs Salt Master, Salt API, and configures authentication
#

set -euo pipefail

# Source common functions
SERVICE_SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=../lib/common.sh
source "${SERVICE_SCRIPT_DIR}/../lib/common.sh"
# shellcheck source=../lib/validators.sh
source "${SERVICE_SCRIPT_DIR}/../lib/validators.sh"

#######################################
# Install SaltStack
# Globals:
#   OS_ID, OS_VERSION
# Returns:
#   0 on success, 1 on failure
#######################################
install_salt() {
  section "Installing SaltStack"

  case "${OS_ID:-ubuntu}" in
    ubuntu|debian)
      install_salt_debian
      ;;
    rocky|almalinux|rhel)
      install_salt_rhel
      ;;
    *)
      fatal "Unsupported OS for Salt installation: ${OS_ID:-unknown}"
      ;;
  esac
}

#######################################
# Install Salt on Debian/Ubuntu
#######################################
install_salt_debian() {
  step "Installing SaltStack for Debian/Ubuntu..."

  # Add Salt repository
  info "Adding Salt repository..."

  # Install required packages for repository
  install_packages curl gnupg

  # Add Salt GPG key
  execute curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public \
    -o /usr/share/keyrings/salt-archive-keyring.pgp

  # Add Salt repository
  case "${OS_VERSION:-24.04}" in
    22.04)
      echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" \
        > /etc/apt/sources.list.d/salt.list
      ;;
    24.04)
      echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" \
        > /etc/apt/sources.list.d/salt.list
      ;;
    *)
      # Debian or other Ubuntu versions
      echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" \
        > /etc/apt/sources.list.d/salt.list
      ;;
  esac

  # Update package lists
  execute apt-get update -qq

  # Install Salt Master and API
  spinner "Installing Salt Master and API" install_packages \
    salt-master salt-api

  success "Salt packages installed"
}

#######################################
# Install Salt on RHEL/Rocky
#######################################
install_salt_rhel() {
  step "Installing SaltStack for RHEL/Rocky..."

  # Add Salt repository
  info "Adding Salt repository..."

  cat > /etc/yum.repos.d/salt.repo << EOF
[salt-repo]
name=Salt Repository
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
gpgcheck=1
gpgkey=https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
enabled=1
EOF

  # Install Salt Master and API
  spinner "Installing Salt Master and API" install_packages \
    salt-master salt-api

  success "Salt packages installed"
}

#######################################
# Create Salt API user
# Arguments:
#   $1 - Username
#   $2 - Password
#######################################
create_salt_api_user() {
  local username="$1"
  local password="$2"

  step "Creating Salt API user: ${username}..."

  # Create system user for Salt API
  if ! user_exists "${username}"; then
    execute useradd -r -s /sbin/nologin -c "Salt API User" "${username}"
    success "Created system user: ${username}"
  else
    info "User ${username} already exists"
  fi

  # Set password for PAM authentication
  echo "${username}:${password}" | execute chpasswd

  success "Salt API user configured"
}

#######################################
# Configure Salt Master
#######################################
configure_salt_master() {
  step "Configuring Salt Master..."

  local master_config="/etc/salt/master.d/veracity.conf"

  # Create master.d directory if it doesn't exist
  mkdir -p /etc/salt/master.d

  # Create Salt Master configuration
  cat > "${master_config}" << EOF
# Veracity - Salt Master Configuration
# Auto-generated by Veracity installer

# Interface to bind to
interface: 0.0.0.0

# Publishing port
publish_port: 4505

# Return port
ret_port: 4506

# Worker threads
worker_threads: 5

# File roots
file_roots:
  base:
    - /srv/salt
    - /srv/salt/states

# Pillar roots
pillar_roots:
  base:
    - /srv/pillar

# Accept new minions automatically (disable for production)
auto_accept: False

# Keep jobs for 24 hours
keep_jobs: 24

# Timeout for minion responses
timeout: 10

# Log level
log_level: info
log_file: /var/log/salt/master

# Event publisher
event_publisher_workers: 5
EOF

  success "Salt Master configuration created"
}

#######################################
# Configure Salt API
#######################################
configure_salt_api() {
  step "Configuring Salt API..."

  local api_config="/etc/salt/master.d/api.conf"

  # Create Salt API configuration
  cat > "${api_config}" << EOF
# Veracity - Salt API Configuration
# Auto-generated by Veracity installer

rest_cherrypy:
  port: 8001
  host: 127.0.0.1
  disable_ssl: True
  webhook_disable_auth: False

external_auth:
  pam:
    ${SALT_API_USER}:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'
EOF

  success "Salt API configuration created"
}

#######################################
# Create Salt directories
#######################################
create_salt_directories() {
  step "Creating Salt directories..."

  # Create directories
  mkdir -p /srv/salt/states
  mkdir -p /srv/pillar
  mkdir -p /var/log/salt

  # Set permissions
  chown -R root:root /srv/salt /srv/pillar
  chmod -R 755 /srv/salt /srv/pillar

  success "Salt directories created"
}

#######################################
# Start Salt services
#######################################
start_salt_services() {
  step "Starting Salt services..."

  # Ensure Salt API has proper systemd dependency on Salt Master
  mkdir -p /etc/systemd/system/salt-api.service.d
  cat > /etc/systemd/system/salt-api.service.d/override.conf << EOF
[Unit]
After=salt-master.service
Requires=salt-master.service

[Service]
# Give Salt Master time to be ready
ExecStartPre=/bin/sleep 5
Restart=on-failure
RestartSec=10
EOF

  execute systemctl daemon-reload

  # Enable and start Salt Master
  execute systemctl enable salt-master
  execute systemctl start salt-master

  if wait_for_service salt-master; then
    success "Salt Master service started"
  else
    fatal "Failed to start Salt Master"
  fi

  # Wait for Salt Master to be fully operational
  info "Waiting for Salt Master to bind to ports..."
  local max_attempts=30
  local attempt=0
  local master_ready=false

  while [ $attempt -lt $max_attempts ]; do
    # Check if Salt Master is listening on both ports
    if ss -tln | grep -q ":4505 " && ss -tln | grep -q ":4506 "; then
      success "Salt Master is listening on ports 4505 and 4506"
      master_ready=true
      break
    fi
    attempt=$((attempt + 1))
    sleep 1
  done

  if [ "$master_ready" != "true" ]; then
    error "Salt Master did not bind to ports after ${max_attempts} seconds"
    info "Checking Salt Master status..."
    systemctl status salt-master --no-pager -l || true
    info "Checking Salt Master logs..."
    journalctl -u salt-master -n 30 --no-pager || true
    fatal "Salt Master failed to start properly"
  fi

  # Additional wait for Salt Master to be fully ready
  info "Waiting for Salt Master to fully initialize..."
  sleep 5

  # Enable and start Salt API
  execute systemctl enable salt-api
  execute systemctl start salt-api

  if wait_for_service salt-api; then
    success "Salt API service started"
  else
    # Salt API often fails on first start, try restarting it
    warning "Salt API failed to start on first attempt, restarting..."
    sleep 2
    execute systemctl restart salt-api
    sleep 3

    if wait_for_service salt-api; then
      success "Salt API started successfully after restart"
    else
      error "Salt API failed to start"
      info "Checking Salt API status..."
      systemctl status salt-api --no-pager -l || true
      info "Checking Salt API logs..."
      journalctl -u salt-api -n 30 --no-pager || true
      fatal "Failed to start Salt API"
    fi
  fi
}

#######################################
# Test Salt API
# Tests authentication and basic functionality
#######################################
test_salt_api() {
  step "Testing Salt API..."

  # Wait for port 8001 to be listening (Salt API takes 10-15 seconds to fully start)
  local max_attempts=30
  local attempt=0

  info "Waiting for Salt API to start serving on port 8001..."
  while [ $attempt -lt $max_attempts ]; do
    if ss -tln | grep -q ":8001 "; then
      success "Salt API is listening on port 8001"
      break
    fi

    attempt=$((attempt + 1))
    sleep 1
  done

  if [ $attempt -eq $max_attempts ]; then
    error "Salt API did not start listening on port 8001 after ${max_attempts} seconds"
    info "Checking Salt API service status..."
    systemctl status salt-api --no-pager -l || true
    info "Checking Salt API logs..."
    journalctl -u salt-api -n 20 --no-pager || true
    fatal "Salt API failed to start properly"
  fi

  # Additional wait for API to be fully ready
  sleep 2

  # Test API endpoint is accessible
  if curl -sSf "http://127.0.0.1:8001" -o /dev/null 2>&1; then
    success "Salt API is accessible"
  else
    fatal "Salt API is not accessible at http://127.0.0.1:8001"
  fi

  # Test authentication
  local token
  token=$(curl -sSk "http://127.0.0.1:8001/login" \
    -H "Accept: application/json" \
    -d username="${SALT_API_USER}" \
    -d password="${SALT_API_PASSWORD}" \
    -d eauth=pam \
    | grep -o '"token": "[^"]*"' | cut -d'"' -f4)

  if [ -n "$token" ]; then
    success "Salt API authentication successful"
    info "Auth token (truncated): ${token:0:20}..."
    return 0
  else
    error "Salt API authentication failed"
    error "Please check credentials and PAM configuration"
    return 1
  fi
}

#######################################
# Generate minion install script
# Creates a script that can be used to install minions
#######################################
generate_minion_install_script() {
  step "Generating minion install script..."

  local minion_script="/opt/server-manager/public/install-minion.sh"
  local master_ip
  master_ip=$(hostname -I | awk '{print $1}')

  mkdir -p /opt/server-manager/public

  cat > "${minion_script}" << 'MINION_EOF'
#!/bin/bash
#
# Veracity Minion Installation Script
# Installs and configures Salt minion to connect to Veracity master
#

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Veracity - Minion Installation${NC}"
echo ""

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
  echo -e "${RED}Error: This script must be run as root${NC}"
  exit 1
fi

# Get master IP (will be replaced by application)
MASTER_IP="__MASTER_IP__"

if [ "$MASTER_IP" == "__MASTER_IP__" ]; then
  read -rp "Enter Salt Master IP address: " MASTER_IP
fi

# Detect OS
if [ -f /etc/os-release ]; then
  . /etc/os-release
  OS_ID="$ID"
else
  echo -e "${RED}Cannot detect operating system${NC}"
  exit 1
fi

echo -e "${GREEN}Installing Salt Minion...${NC}"

# Install based on OS
case "${OS_ID}" in
  ubuntu|debian)
    curl -fsSL https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public -o /usr/share/keyrings/salt-archive-keyring.pgp
    echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main" > /etc/apt/sources.list.d/salt.list
    apt-get update -qq
    DEBIAN_FRONTEND=noninteractive apt-get install -y -qq salt-minion
    ;;
  rocky|almalinux|rhel|centos)
    cat > /etc/yum.repos.d/salt.repo << EOF
[salt-repo]
name=Salt Repository
baseurl=https://packages.broadcom.com/artifactory/saltproject-rpm/
gpgcheck=1
gpgkey=https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
enabled=1
EOF
    dnf install -y -q salt-minion
    ;;
  *)
    echo -e "${RED}Unsupported OS: ${OS_ID}${NC}"
    exit 1
    ;;
esac

# Configure minion
cat > /etc/salt/minion.d/veracity.conf << EOF
master: ${MASTER_IP}
master_port: 4506
id: $(hostname -f)
EOF

# Start and enable minion
systemctl enable salt-minion
systemctl restart salt-minion

echo -e "${GREEN}Salt Minion installed successfully!${NC}"
echo ""
echo -e "Minion ID: $(hostname -f)"
echo -e "Master IP: ${MASTER_IP}"
echo ""
echo -e "Next steps:"
echo -e "1. Accept this minion's key on the master:"
echo -e "   ${BLUE}salt-key -a $(hostname -f)${NC}"
echo -e "2. Test connection:"
echo -e "   ${BLUE}salt $(hostname -f) test.ping${NC}"
MINION_EOF

  chmod 755 "${minion_script}"

  # Replace master IP placeholder if we know it
  if [ -n "${master_ip}" ]; then
    sed -i "s/__MASTER_IP__/${master_ip}/" "${minion_script}"
  fi

  success "Minion install script generated: ${minion_script}"
}

#######################################
# Setup SaltStack for Veracity
# Main function that orchestrates Salt setup
# Globals:
#   SALT_API_USER, SALT_API_PASSWORD
#######################################
setup_salt() {
  install_salt
  create_salt_api_user "${SALT_API_USER}" "${SALT_API_PASSWORD}"
  configure_salt_master
  configure_salt_api
  create_salt_directories
  start_salt_services
  test_salt_api
  generate_minion_install_script

  # Display Salt info
  info "Salt version: $(salt --version | head -1)"
  info "Salt Master: http://127.0.0.1:8001"
  info "Salt API User: ${SALT_API_USER}"

  success "SaltStack setup complete!"
}

# If script is executed directly, run setup
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  if [ -z "${SALT_API_USER:-}" ] || [ -z "${SALT_API_PASSWORD:-}" ]; then
    fatal "Required environment variables not set: SALT_API_USER, SALT_API_PASSWORD"
  fi

  setup_salt
fi
